/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  mainSidebar: [
    'about',
    'changelog',
    {
      type: 'category',
      label: '🎮 H1-Mod',
      collapsible: false,
      items: [
        'install',
        'update',
        'uninstall',
      ]
    },
    {
      type: 'category',
      label: '🎮 IW7-Mod',
      collapsible: false,
      items: [
        'iw7-install',
        'iw7-update',
        'iw7-uninstall',
        'iw7-server-guide',
      ]
    },
    {
      type: 'category',
      label: '🛠 Support',
      collapsible: false,
      items: [
        'troubleshoot',
        'errors',
        'port-forwarding',
        'functions',
        'ingamename',
        'languages',
        'colorcodes',
      ]
    },
    {
      type: 'category',
      label: '💻 Scripting',
      collapsible: true,
      items: [
        'gsc-scripting',
        'gsc-load-script',
        'gsc-scripting-syntax',
        'gsc-dump',
        'ui-scripting'
      ]
    },
    {
      type: 'category',
      label: '👾 Zonetool',
      collapsible: true,
      items: [
        'zonetool-basics',
        'map-porting-iw5',
        'map-porting-s1',
        'map-arena-files'
      ]
    },
    {
      type: 'category',
      label: '💣 Extra',
      collapsible: true,
      items: [
        'antialiasing',
        'ds4windows',
        'fullbright',
      ]
    },
  ],
};

module.exports = sidebars;
